/**
 * @fileoverview Lean project initialization
 * @module @nahisaho/musubix-lean/environment
 * @traceability REQ-LEAN-CORE-002
 */

import { mkdir, writeFile, access } from 'node:fs/promises';
import { join } from 'node:path';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import type { LeanConfig } from '../types.js';
import { LeanFileGenerationError } from '../errors.js';

const execAsync = promisify(exec);

/**
 * Options for project initialization
 */
export interface InitializeOptions {
  /** Project name */
  name: string;
  /** Target directory */
  directory: string;
  /** Include Mathlib dependency */
  useMathlib?: boolean;
  /** Custom lakefile content */
  customLakefile?: string;
}

/**
 * Initialize a new Lean 4 project
 * @traceability REQ-LEAN-CORE-002
 */
export async function initializeLeanProject(
  options: InitializeOptions
): Promise<void> {
  const { name, directory, useMathlib = false } = options;

  try {
    // Create directory structure
    await mkdir(directory, { recursive: true });
    await mkdir(join(directory, name), { recursive: true });

    // Generate lakefile.lean
    const lakefileContent =
      options.customLakefile || generateLakefile(name, useMathlib);
    await writeFile(join(directory, 'lakefile.lean'), lakefileContent, 'utf-8');

    // Generate lean-toolchain
    await writeFile(join(directory, 'lean-toolchain'), 'leanprover/lean4:stable\n', 'utf-8');

    // Generate Main.lean
    const mainContent = generateMainLean(name);
    await writeFile(join(directory, `${name}.lean`), mainContent, 'utf-8');

    // Generate MUSUBIX tactics library
    const tacticsContent = generateMusubixTactics();
    await writeFile(
      join(directory, name, 'Tactics.lean'),
      tacticsContent,
      'utf-8'
    );

    // Generate basic definitions
    const basicsContent = generateBasics();
    await writeFile(
      join(directory, name, 'Basics.lean'),
      basicsContent,
      'utf-8'
    );

    // Run lake build to verify setup
    try {
      await execAsync('lake build', { cwd: directory, timeout: 60000 });
    } catch {
      // Build failure is acceptable for initial setup
      // The user may need to configure Lean first
    }
  } catch (error) {
    throw new LeanFileGenerationError(
      directory,
      error instanceof Error ? error.message : String(error)
    );
  }
}

/**
 * Generate lakefile.lean content
 */
function generateLakefile(name: string, useMathlib: boolean): string {
  let content = `import Lake
open Lake DSL

package «${name}» where
  version := v!"0.1.0"
  keywords := #["musubix", "verification"]
  leanOptions := #[
    ⟨\`pp.unicode.fun, true⟩,
    ⟨\`autoImplicit, false⟩
  ]

`;

  if (useMathlib) {
    content += `require mathlib from git
  "https://github.com/leanprover-community/mathlib4"

`;
  }

  content += `@[default_target]
lean_lib «${name}» where
  srcDir := "."
  roots := #[\`${name}]
`;

  return content;
}

/**
 * Generate main Lean file content
 */
function generateMainLean(name: string): string {
  return `/-
  ${name} - MUSUBIX Verification Project
  
  This project contains formal verification proofs generated by MUSUBIX.
  Requirements are converted from EARS format to Lean theorems.
-/

import ${name}.Tactics
import ${name}.Basics

namespace ${name}

-- Requirements will be added here by MUSUBIX

end ${name}
`;
}

/**
 * Generate MUSUBIX tactics library
 */
function generateMusubixTactics(): string {
  return `/-
  MUSUBIX Custom Tactics
  
  This module provides custom tactics for verifying MUSUBIX requirements.
-/

namespace Musubix.Tactics

/-- Try common tactics in sequence -/
macro "musubix_auto" : tactic =>
  \`(tactic| first
    | rfl
    | decide
    | simp [*]
    | trivial
    | assumption
    | contradiction)

/-- Verify a requirement with common patterns -/
macro "verify_req" : tactic =>
  \`(tactic| (
    try intros
    try simp only []
    try musubix_auto
    try omega
  ))

/-- Split goals for event-driven requirements -/
macro "split_event" : tactic =>
  \`(tactic| (
    intro h_event
    constructor <;> try musubix_auto
  ))

end Musubix.Tactics
`;
}

/**
 * Generate basic definitions for MUSUBIX verification
 */
function generateBasics(): string {
  return `/-
  MUSUBIX Basic Definitions
  
  Common types and predicates used in MUSUBIX verification.
-/

namespace Musubix

/-- Result type for operations that can fail -/
inductive Result (α : Type) (ε : Type) where
  | ok : α → Result α ε
  | err : ε → Result α ε

/-- Check if result is successful -/
def Result.isOk {α ε : Type} : Result α ε → Bool
  | .ok _ => true
  | .err _ => false

/-- Check if result is an error -/
def Result.isErr {α ε : Type} : Result α ε → Bool
  | .ok _ => false
  | .err _ => true

/-- Natural number bounds predicate -/
def InRange (n : Nat) (lo hi : Nat) : Prop :=
  lo ≤ n ∧ n ≤ hi

/-- Integer bounds predicate -/
def IntInRange (n : Int) (lo hi : Int) : Prop :=
  lo ≤ n ∧ n ≤ hi

/-- Non-empty string predicate -/
def NonEmptyString (s : String) : Prop :=
  s.length > 0

/-- Valid identifier predicate -/
def ValidIdentifier (s : String) : Prop :=
  s.length > 0 ∧ s.all (fun c => c.isAlphanum || c == '_')

end Musubix
`;
}

/**
 * Check if a Lean project exists at the given path
 */
export async function isLeanProject(directory: string): Promise<boolean> {
  try {
    await access(join(directory, 'lakefile.lean'));
    return true;
  } catch {
    return false;
  }
}

/**
 * LeanProjectInitializer class implementation
 * @traceability REQ-LEAN-CORE-002
 */
export class LeanProjectInitializer {
  constructor(private readonly config: Partial<LeanConfig> = {}) {}

  /**
   * Initialize a new Lean project
   */
  async initialize(options: InitializeOptions): Promise<void> {
    return initializeLeanProject({
      ...options,
      useMathlib: options.useMathlib ?? this.config.mathlibEnabled,
    });
  }

  /**
   * Check if directory is already a Lean project
   */
  async isProject(directory: string): Promise<boolean> {
    return isLeanProject(directory);
  }

  /**
   * Add MUSUBIX module to existing project
   */
  async addMusubixModule(directory: string): Promise<void> {
    const musubixDir = join(directory, 'Musubix');
    await mkdir(musubixDir, { recursive: true });
    await writeFile(
      join(musubixDir, 'Tactics.lean'),
      generateMusubixTactics(),
      'utf-8'
    );
    await writeFile(
      join(musubixDir, 'Basics.lean'),
      generateBasics(),
      'utf-8'
    );
  }
}
